# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VrmState.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VrmState.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eVrmState.proto\"\xfd\x01\n\x0fVrmStateMessage\x12\x16\n\x0e\x62linkLeftValue\x18\x01 \x01(\x02\x12\x17\n\x0f\x62linkRightValue\x18\x02 \x01(\x02\x12\x15\n\rheadRotationX\x18\x03 \x01(\x02\x12\x15\n\rheadRotationY\x18\x04 \x01(\x02\x12\x14\n\x0cjawRotationX\x18\x05 \x01(\x02\x12\x14\n\x0cjawRotationY\x18\x06 \x01(\x02\x12\x0f\n\x07lookAtX\x18\x07 \x01(\x02\x12\x0f\n\x07lookAtY\x18\x08 \x01(\x02\x12\x0f\n\x07lookAtZ\x18\t \x01(\x02\x12\x15\n\rneckRotationX\x18\n \x01(\x02\x12\x15\n\rneckRotationY\x18\x0b \x01(\x02\x62\x06proto3'
)




_VRMSTATEMESSAGE = _descriptor.Descriptor(
  name='VrmStateMessage',
  full_name='VrmStateMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blinkLeftValue', full_name='VrmStateMessage.blinkLeftValue', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blinkRightValue', full_name='VrmStateMessage.blinkRightValue', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headRotationX', full_name='VrmStateMessage.headRotationX', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headRotationY', full_name='VrmStateMessage.headRotationY', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jawRotationX', full_name='VrmStateMessage.jawRotationX', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='jawRotationY', full_name='VrmStateMessage.jawRotationY', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lookAtX', full_name='VrmStateMessage.lookAtX', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lookAtY', full_name='VrmStateMessage.lookAtY', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lookAtZ', full_name='VrmStateMessage.lookAtZ', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='neckRotationX', full_name='VrmStateMessage.neckRotationX', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='neckRotationY', full_name='VrmStateMessage.neckRotationY', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=272,
)

DESCRIPTOR.message_types_by_name['VrmStateMessage'] = _VRMSTATEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VrmStateMessage = _reflection.GeneratedProtocolMessageType('VrmStateMessage', (_message.Message,), {
  'DESCRIPTOR' : _VRMSTATEMESSAGE,
  '__module__' : 'VrmState_pb2'
  # @@protoc_insertion_point(class_scope:VrmStateMessage)
  })
_sym_db.RegisterMessage(VrmStateMessage)


# @@protoc_insertion_point(module_scope)
