name: client

on:
  push:

jobs:
  pre-test:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["openvtuber-client/**", ".github/workflows/client.yml"]'


  test:
    needs: pre-test
    if: ${{ needs.pre-test.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openvtuber-client
    strategy:
      matrix:
        node: ['12']
    name: Testing openvtuber's client with node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies and script
        run: yarn

      - name: Run TypeScript compiler
        run: yarn run tsc

      - name: Check linting with eslint
        run: yarn run lint:check

      - name: Check formatting with prettier
        run: yarn run format:check

      - name: Test
        run: yarn run test:ci

