name: client

on:
  push:
    paths:
    - 'openvtuber-client/**'
    - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openvtuber-client
    strategy:
      matrix:
        node: ['12']
    name: Testing openvtuber with node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies and script
        run: yarn

      - name: Run TypeScript compiler
        run: yarn run tsc

      - name: Check linting with eslint
        run: yarn run lint:check

      - name: Check formatting with prettier
        run: yarn run format:check

      - name: Test
        run: yarn run test

