name: deploy client

on:
  push:
    branches:
    - master
    paths:
    - 'openvtuber-client/**'
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openvtuber-client
    name: Building docs with node 12
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies and script
        run: yarn

      - name: Build
        run: yarn run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'openvtuber-server/src/openvtuber/client'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

