name: deploy client

on:
  push:
    branches:
    - master
    paths:
    - 'openvtuber-client/**'
    - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openvtuber-client
    name: Building docs with node 12
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies and script
        run: yarn

      - name: Build
        run: yarn run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../openvtuber-server/src/openvtuber/client

