name: docs

on:
  push:
    paths:
    - 'docs/**'
    - '.github/workflows/**'

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: docs
    name: Linting docs with node 12
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies and script
        run: yarn

      - name: Spell check
        run: yarn run spell:check

      - name: Style check
        run: yarn run style:check

