name: docs

on:
  push:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["docs/**", ".github/workflows/docs.yml"]'
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    name: Linting docs with node 12
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies and script
        run: yarn

      - name: Spell check
        run: yarn run spell:check

      - name: Style check
        run: yarn run style:check

