name: mobile

on:
  push:
    paths:
    - 'openvtuber-mobile-client/**'
    - '.github/workflows/**'

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: openvtuber-mobile-client
    name: Testing openvtuber with Dart
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.4'
      - run: flutter pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze code
        run: dart analyze --fatal-infos
      - run: flutter test
