name: release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  test-server:
    runs-on: ubuntu-latest
    name: Testing openvtuber server
    strategy:
      matrix:
        python: ["3.8", "3.9"]
    defaults:
      run:
        working-directory: openvtuber-server
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install test dependencies and script
        run: pip install .[tests]

      - name: Install dependencies and script
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8

      - name: Run static type analyzer
        run: mypy

      - name: Test with pytest
        run: pytest tests/

  test-client:
    runs-on: ubuntu-latest
    name: Testing openvtuber client
    strategy:
      matrix:
        node: ["12"]
    defaults:
      run:
        working-directory: openvtuber-client
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies and script
        run: yarn

      - name: Run TypeScript compiler
        run: yarn run tsc

      - name: Check linting with eslint
        run: yarn run lint:check

      - name: Check formatting with prettier
        run: yarn run format:check

      - name: Test
        run: yarn run test

  build-app:
    runs-on: ubuntu-latest
    name: Releasing openvtuber
    needs: [test-server, test-client]
    steps:
      - name: Build client
        run: |
          yarn install
          yarn run build
        working-directory: openvtuber-client

      - name: Build server
        run: |
          pip3 install --upgrade pip setuptools wheel
          python setup.py sdist bdist_wheel
        working-directory: openvtuber-server

      - name: Set value for version
        run: echo "VERSION=$(python setup.py --version)" >> $GITHUB_ENV
        working-directory: openvtuber-server

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload source distribution
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openvtuber-server/dist/openvtuber-$VERSION.tar.gz
          asset_name: openvtuber-$VERSION.tar.gz
          asset_content_type: application/tar+gzip

      - name: Upload wheel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openvtuber-server/dist/openvtuber-$VERSION-py3-none-any.whl
          asset_name: openvtuber-$VERSION-py3-none-any.whl
          asset_content_type: application/x-wheel+zip
