name: server

on:
  push:
    paths:
    - 'openvtuber-server/**'
    - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openvtuber-server
    strategy:
      matrix:
        python: ['3.8', '3.9']
    name: Testing openvtuber with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Cython
        run: pip install Cython

      - name: Install test dependencies and script
        run: pip install .[tests]

      - name: Lint with flake8
        run: flake8
      
      - name: Run static type analyzer
        run: mypy
      
      - name: Test with pytest
        run: pytest tests/
