name: server

on:
  push:

jobs:
  pre-test:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["openvtuber-server/**", ".github/workflows/server.yml"]'

  test:
    needs: pre-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openvtuber-server
    strategy:
      matrix:
        python: ['3.8', '3.9']
    name: Testing openvtuber's server with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ needs.pre-test.outputs.should_skip != 'true' }}
      - name: Setup python
        uses: actions/setup-python@v2
        if: ${{ needs.pre-test.outputs.should_skip != 'true' }}
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/cache@v2
        if: ${{ needs.pre-test.outputs.should_skip != 'true' }}
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Cython
        if: ${{ needs.pre-test.outputs.should_skip != 'true' }}
        run: pip install Cython --upgrade --upgrade-strategy eager

      - name: Install test dependencies and script
        if: ${{ needs.pre-test.outputs.should_skip != 'true' }}
        run: pip install .[tests] --upgrade --upgrade-strategy eager

      - name: Lint with flake8
        if: ${{ needs.pre-test.outputs.should_skip != 'true' }}
        run: flake8
      
      - name: Run static type analyzer
        if: ${{ needs.pre-test.outputs.should_skip != 'true' }}
        run: mypy
      
      - name: Test with pytest
        if: ${{ needs.pre-test.outputs.should_skip != 'true' }}
        run: pytest tests/
